kind: Service
apiVersion: v1
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name: http
      port: 80
      nodePort: 30080
      

  type: NodePort
---
  
kind: Service
apiVersion: v1
metadata:
  name: fleetman-activemq

spec:
  selector:
    app: activemq
    release: "1"

  ports:
    - name: http
      port: 8161
      nodePort: 30010
      

  type: NodePort